### PR TITLE
The node buttons render incorrectly

### LINKED ISSUE #78: The node buttons render incorrectly after navigation away and back
**Describe the bug**
Rendering of nodes in build page should render the same each time.

**To Reproduce**

1. Goto http://localhost:3000/builder
2. Hover over topoaa node, it should look like :

localhost_3000_builder

3. Navigate to About page and back to build page. The topoaa node on hover now looks like

localhost_3000_

**Workaround**
Refreshing the page. The topoaa node on hover now looks like same as first time.

**Expected behavior**
The topoaa node on hover the second time looks the same as the first time.

### PR DESCRIPTION
**Pull request by dmijatovic**
#  The node buttons render incorrectly after switching between pages

Closes #78 

This should fix issue with workflow buttons after switching between app pages.

## Changes made
- Upgrade to core v2 (to address #78)
- Extended builder styles:
   - added bootstrap styles for custom-select
   - added bootstrap styles for popover
   - added bootstrap styles for missing `col-x` classes
   - removed background color for input file type
   - added specific button formatting for new core v2 classes
- Moved css import from builder.tsx to Form.client.tsx imports and removed styles.ts import of table and react toastify styles (these styles seem to be already included - not sure where/how).
- Added gap between buttons
- Removed some div elements
- Defined max/min width of builder page between 800-1600px

## How to test

- Run app and switch between pages, confirm that initial issue #78 is solved
- Confirm that select elements are styled
- Confirm that tables have working popover
- Change theme light/dark and confirm that styles of select and popover are updated

### CODE REVIEW

File: app/routes/builder.tsx [hunk 1]
```diff
@@ -12,7 +12,6 @@ import { ClientOnly } from "~/components/ClientOnly";
 import { getOptionalUser, mustBeAllowedToSubmit } from "~/auth.server";
 import { getBartenderTokenByUser } from "~/bartender-client/token.server";
 import { Haddock3WorkflowBuilder } from "~/builder/Form.client";
-import { haddock3Styles } from "~/builder/styles";
```
Comment (sverhoeven) [inline app/routes/builder.tsx:15]: The `app/builder/styles.ts` file is also used at app/routes/jobs.$id.edit.tsx:31:31 .  Very strange even if I remove the styles.ts and the import in edit route the toast still works. It must come with its own inlined style.

Can you remove the styles.ts and the import of it in *edit.tsx route?

**Review by sverhoeven — APPROVED** [review]
Looks great. Learning some css from you.
The node buttons retain their style after navigating away and back.
The select and tables look good. 
In dark mode the table tooltips are still light, it would be nice if they could be dark in dark mode.

Could you also remove the styles.ts, see inline comment?

**Review by sverhoeven — APPROVED** [review]
Table popup in dark mode is correct now.

The edit page is rendered unstyled.
Can you add `className="workflow-builder-app m-auto min-w-[50rem] max-w-[100rem]"`  to the  main tag in app/routes/jobs.$id.edit.tsx .
Once you have fixed the edit page then its ok to merge.
